version: "3.0"

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    image: nginx
    restart: always
    volumes:
      - wp_volume:/var/www/html/wordpress
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - inception_network
    tty: true

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    image: mariadb
    restart: always
    expose:
      - "3306"
    volumes:
      - db_volume:/var/lib/mysql/ #[호스트 디렉토리 경로]:[컨테이너 디렉토리 경로]
    env_file:
      - .env
    networks:
      - inception_network
    tty: true

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    image: wordpress
    restart: always
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - wp_volume:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - inception_network

  website:
    container_name: website
    build: requirements/bonus/website/
    image: website
    networks:
      - inception_network
    ports:
      - "7777:7777"
    restart: always

  backup:
    container_name: backup
    build: requirements/bonus/backup/
    image: backup
    networks:
      - inception_network
    depends_on:
      - mariadb
    volumes:
      - db_volume:/db_volume
      - backup_db_volume:/backup
    restart: always
    env_file:
      - .env


volumes:
  db_volume:
    driver: local
    driver_opts:
      type: volume
      device: /home/sham/data/mariadb
      o: bind

  wp_volume:
    driver: local
    driver_opts:
      type: volume
      device: /home/sham/data/wordpress
      o: bind
  backup_db_volume:
    driver_opts:
      type: volume
      device: /home/sham/data/backupMariadb
      o: bind


networks:
  inception_network:
    driver: bridge
